# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'FoodyWeather' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for FoodyWeather
	pod 'lottie-ios'
	pod 'Kingfisher', '~> 5.0'

  target 'FoodyWeatherTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'FoodyWeatherUITests' do
    # Pods for testing
  end

end
